config/routes.rb
Rails.application.routes.draw do
  resources :messages, only: %i[new create] do
    post 'contact_mailer'
  end

  resources :languages
  resources :projects
  devise_for :users
  root 'projects#index' # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :languages_projects
  has_many :projects, through: :languages_projects

  has_one_attached :picture

  validates :name, presence: true
end

app/models/languages_project.rb
class LanguagesProject < ApplicationRecord
  belongs_to :project
  belongs_to :language
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :phone_number, :body
  validates :name, :email, :body, presence: true
  validates_format_of :email,
                      with: /\A[^@,\s]+@[^@,\s]+\.[^@,\s]+\z/,
                      message: 'Veuillez entrer une adresse email valide.'
  validates :body, presence: { message: "Tu as oublié d'écrire ton message !" }
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :languages_projects
  has_many :languages, through: :languages_projects

  has_one_attached :picture
  validates :title, :description, :url, presence: true
end

app/models/user.rb
class User < ApplicationRecord # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable # Include default devise modules. Others available are:
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email password])
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :authenticate_user!, only: %i[create edit update destroy]

  # GET /languages
  # GET /languages.json
  def index
    @languages = Language.all
  end

  # GET /languages/1
  # GET /languages/1.json
  def show
    set_language
  end

  # GET /languages/new
  def new
    @language = Language.new
  end

  # GET /languages/1/edit
  def edit
    @language = set_language
  end

  # POST /languages
  # POST /languages.json
  def create
    @language = Language.new(language_params)

    respond_to do |format|
      if @language.save
        format.html do
          redirect_to @language, notice: 'Language was successfully created.'
        end
        format.json { render :show, status: :created, location: @language }
      else
        format.html { render :new }
        format.json do
          render json: @language.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /languages/1
  # PATCH/PUT /languages/1.json
  def update
    respond_to do |format|
      if set_language.update(language_params)
        format.html do
          redirect_to set_language, notice: 'Language was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @language }
      else
        format.html { render :edit }
        format.json do
          render json: set_language.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /languages/1
  # DELETE /languages/1.json
  def destroy
    set_language.destroy
    respond_to do |format|
      format.html do
        redirect_to languages_url,
                    notice: 'Language was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private # Use callbacks to share common setup or constraints between actions.
  def set_language
    @language = Language.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def language_params
    params.require(:language).permit(:name, :picture)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end
  def create
    @message = Message.new message_params
    if @message.valid?
      MessageMailer.contact_email_from_user(@message).deliver_now
      redirect_to new_message_url
      flash[:notice] =
        'We have received your message and will be in touch soon!'
    else
      flash[:notice] =
        'There was an error sending your message. Please try again.'
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :phone_number, :body)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create update destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
  end

  # GET /projects/new
  def new
    @project = Project.new
    @message = Message.new
  end

  # GET /projects/1/edit
  def edit
    set_project
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @message = Message.new message_params
    if @message.valid?
      MessageMailer.contact(@message).deliver_now
      redirect_to new_message_url
      flash[:notice] =
        'We have received your message and will be in touch soon!'
    else
      flash[:notice] =
        'There was an error sending your message. Please try again.'
      render :new
    end
    respond_to do |format|
      if @project.save
        format.html do
          redirect_to @project, notice: 'Project was successfully created.'
        end
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json do
          render json: @project.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if set_project.update(project_params)
        format.html do
          redirect_to @project, notice: 'Project was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json do
          render json: @project.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    set_project.destroy
    respond_to do |format|
      format.html do
        redirect_to projects_url, notice: 'Project was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def project_params
    params.require(:project).permit(:title, :description, :url, :picture)
  end
  def message_params
    params.require(:message).permit(:name, :email, :phone_number, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/languages/_form.html.erb
<%= simple_form_for(@language) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%=f.input :picture,as: :file%>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/languages/edit.html.erb
<h1>Editing Language</h1>

<%= render 'form', language: @language %>

<%= link_to 'Show', @language %> |
<%= link_to 'Back', languages_path %>

app/views/languages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Languages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @languages.each do |language| %>
      <tr>
        <td><%= language.name %></td>
        <td><%= link_to 'Show', language %></td>
        <td><%= link_to 'Edit', edit_language_path(language) %></td>
        <td><%= link_to 'Destroy', language, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Language', new_language_path %>

app/views/languages/new.html.erb
<h1>New Language</h1>

<%= render 'form', language: @language %>

<%= link_to 'Back', languages_path %>

app/views/languages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @language.name %>
</p>

<%= link_to 'Edit', edit_language_path(@language) %> |
<%= link_to 'Back', languages_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand navbar-dark bg-dark" aria-label="Second navbar example">
  <div class="container-fluid d-flex flex-row justify-content-between">
    <div class="logo">
      <%=link_to root_path do%>
        <%=image_tag "https://res.cloudinary.com/dtevenab3/image/upload/v1608212768/115536698_653264105604624_4096573005137404116_n_srha9q_waegcd.png",class:"imagenav"%>
      <% end %>
    </div>
    <%if current_user%>
      <%=link_to "déconexion",destroy_user_session_path, method:'DELETE', class:"text-white btn btn-warning my-3  d-none "%>
    <% else %>
      <%=link_to "Connexion",user_session_path, class:"text-white btn btn-nav m-auto  d-none " %>
    <% end %>
    <div class="follow">
      <a href="https://github.com/piwiit"><i class="fab fa-github fa-2x mx-2 "></i></a>
      <a href="https://twitter.com/PiwiitJo"><i class="fab fa-twitter-square fa-2x mx-2 "></i></a>
      <a href="https://www.linkedin.com/in/jonathan-bouillaux-810b831a1/"><i class="fab fa-linkedin fa-2x mx-2 "></i></a>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# js annimation %>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/25d75193a7.js" crossorigin="anonymous"></script>
    <script type="text/javascript" src="./public/theme/js/t-scroll.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>
  <body >
    <%= render 'layouts/navbar'%>
    <%= yield %>
  </body>
</html>

app/views/messages/new.html.erb
<div class="jumbotron">
  <%= simple_form_for(@message) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :phone_number %>
    <%= f.input :body%>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/projects/_body.html.erb
<div class="media m-3">
  <img src="https://res.cloudinary.com/dtevenab3/image/upload/v1608659126/image_iwld72.png" alt="profile picture" class='align-self-center rounded m-2 pr-3'>
  <div class="media-body">
    <h3 class="mt-4 ">About-me</h3>
    <p class=' pr-5'>After several experiences in restaurants and shops, I chose to deepen my affinity for programming. So I decided to take classes on openclassroom. It was while spending day and night there for a month that I met privateers from The hacking Project, motivating me to take this training. Today I am in my turn privateer of the  hacking Project, armed with a flamboyant passion for code and the desire to <span> learn more and more.</span> I continue to learn my skills by continuing to develop applications every week.</p>
  </div>
</div>

app/views/projects/_form.html.erb
<div class="jumbotron">
  <%= simple_form_for(@project) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :url %>
    <%= f.input :picture%>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/projects/_header.html.erb
<main class=' flag'>
  <section class="py-5 text-center container">
    <div class="row py-lg-5  ">
      <div class="col-lg-6 col-md-8 mx-auto bold text-landing">
        <h1 class="font-weight-bold  ">Hello there !</h1>
        <p class="  font-weight-bold ">I'm <span>Jonathan Bouillaux</span> and I'm Web developper</p>
        <i class="far fa-gem fa-3x text-danger mb-5 zoomIn t-animated" data-t-show="1"></i>
      </div>
    </div>
  </section>
</main>

app/views/projects/_projects.html.erb
<div  id="div-projects-title"> My projects </div>
<div class="album py-5 bg-white">
  <div class="container">
    <div class="row justify-content-center">
      <% unless @projects.present? %>
        <h3>Pas de projet validé à ce jours</h3>
      <% end %>
      <% @projects.each do |project| %>
        <div class="col-lg-4 col-sm-12 portfolio-item rounded  ">
          <div class="card h-100 p-1 zoomIn">
            <% if project.picture.attached?%>
              <%= image_tag "discotroc.png",class:"card-img-top"%>
            <% end %>
            <!-- Card content -->
            <div class="card-body p-1 bg-white rounded m-1">
              <h4 class="card-title ">
                <%= truncate(project.title, length: 50) %> :</h4>
              <p class="card-text "><%= truncate(project.description, length: 100) %></p>
            </div>
            <!-- Button -->
            <%= link_to  "En lire plus", project_path(project.id),class:'btn btn-warning' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/_skills.html.erb
<div class="jumbotron ">
  <div id="div-skills-bars">
    <div id="div-skills-title"> My skills </div>
    <div id="bars-all">
      <div id="bar-large">
        <div id="bar-name"> HTML / CSS </div>
        <div id="bar-medium"></div>
        <div id="bar-small-90"></div>
      </div>
      <div id="bar-large">
        <div id="bar-name"> Ruby / RoR </div>
        <div id="bar-medium"></div>
        <div id="bar-small-60"></div>
      </div>
      <div id="bar-large">
        <div id="bar-name"> SQL </div>
        <div id="bar-medium"></div>
        <div id="bar-small-50"></div>
      </div>
      <div id="bar-large">
        <div id="bar-name"> JavaScript </div>
        <div id="bar-medium"></div>
        <div id="bar-small-20"></div>
      </div>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<%= render 'header'%>
<%= render 'body'%>
<%= render 'skills'%>
<% if current_user %>
  <%= link_to 'New Project', new_project_path,class:"btn btn-warning my-3 " %>
<% end %>
<%= render 'projects'%>
<%# <%= render 'messages/new'%> %>
<script>
  let buttonClick = document.querySelector("body > main > section > div > div > i")
  let userLogin = document.querySelector("body > nav > div > a")
  function onClickUserLogin() {
    userLogin.classList.toggle("d-none");
  }
  buttonClick.addEventListener("click", onClickUserLogin);
</script>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>
<%= render 'form', project: @project %>
<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>
<main role="main ">
  <section class="jumbotron ">
    <h1 class="jumbotron-heading text-center"><%=@project.title%></h1>
    <% if @project.picture.attached?%>
      <%= image_tag "discotroc.png",class:"card-img-top"%>
    <% end %>
    <ul class="list-group list-group-flush">
      <li class="list-group-item"><i class="fas fa-stream"></i> : <%=@project.description%></li>
      <li class="list-group-item"><%=link_to "accéder au site" ,@project.url ,class:"btn btn-warning"%> <%= link_to 'retour', projects_path ,class:"btn btn-warning"%></li>
    </ul>
  </section>
</main>